export default {
  products: [
    {
      id: 1,
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/1.jpeg",
      price: 60,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 2,
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/1.jpeg",
      price: 50,
      brand: "Levis",
      rating: 4.2,
      reviews: 5,
    },
    {
      id: 3,
      name: "Blouse",
      category: "Blouse",
      image: "/images/1.jpeg",
      price: 60,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 4,
      name: "Best Pants",
      category: "Pants",
      image: "/images/1.jpeg",
      price: 70,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 5,
      name: "Light Short",
      category: "Sorts",
      image: "/images/1.jpeg",
      price: 60,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
    {
      id: 6,
      name: "Rock Jeans",
      category: "Jeans",
      image: "/images/1.jpeg",
      price: 60,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
  ],
};
