export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/1.jpeg",
      price: 60,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/2.jpg",
      price: 50,
      brand: "Levis",
      rating: 4.2,
      reviews: 5,
    },
    {
      _id: "3",
      name: "Blouse",
      category: "Blouse",
      image: "/images/3.jpg",
      price: 60,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
    {
      _id: "4",
      name: "Best Pants",
      category: "Pants",
      image: "/images/4.jpg",
      price: 70,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
    {
      _id: "5",
      name: "Light Short",
      category: "Sorts",
      image: "/images/5.jpg",
      price: 60,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
    {
      _id: "6",
      name: "Rock Jeans",
      category: "Jeans",
      image: "/images/6.jpg",
      price: 60,
      brand: "Levis",
      rating: 4.5,
      reviews: 10,
    },
  ],
};
